services:
  my-portfolio:
    build: .
    container_name: leche_lanzema_coding_assignment14
    ports:
      - "5575:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - .:/app
