version: "3"
services:
  my-portfolio:
    build: .
    container_name: abdulai_abubakar_coding_assignmnet14
    ports:
      - "5575:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    volumes:
      - .:/app
